#!/usr/bin/env bash
# This script configures localhost and facebook.com IP resolution

cp /etc/hosts /tmp/hosts_new

sed 's/127\.0\.0\.1[[:space:]]\+localhost/127.0.0.2 localhost/' /tmp/hosts_new > /tmp/hosts_fixed

echo "8.8.8.8 facebook.com" >> /tmp/hosts_fixed

cat /tmp/hosts_fixed > /etc/hosts
